### ISSUE TITLE
Formatting Questions

### ISSUE THREAD

**Issue by cdcv** [MaazAli/highcharts-gauge#3]
Can you provide a bit of guidance on how to do the gauge formatting?  How do you perform formatting of style elements that aren't indicated in your demo examples?
I looked at your examples.
For example, how do you remove the (currently white) gauge background to make it transparent?
Thanks.

**Comment by jhuenges** [comment]
If you want to change the background color of a chart you can add `backgroundColor: '<hex color>'` at [this](https://github.com/jhuenges/highcharts-demo/blob/master/client/demos/gaugeDemo.js#L8) line (or every other chart ;) ). To make it transparent simple add `backgroundColor: ''` (without a color). For more styling options and explanations you can take a look at the [official documentation](http://www.highcharts.com/docs/chart-design-and-style/design-and-style) for highcharts.
If you need more help, feel free to ask!

**Comment by cdcv** [comment]
Thanks!
